import { StudyProtocol } from "../types";
import { STANDARD_CODELISTS, scaffoldCdashDomain } from "../cdisc-cdash-library";

export const ONCOLOGY_RECIST_PRESET: StudyProtocol = {
  id: "study_onc_003",
  protocolNumber: "ONC-2026-003",
  studyName: "A Randomized, Double-Blind Phase III Study of Dual Immune Checkpoint Inhibition in Advanced Solid Tumors",
  phase: "Phase III",
  sponsor: "Aura Oncology Therapeutics",
  therapeuticArea: "Oncology",
  version: "3.2",
  lastModified: "2026-08-15",
  branding: {
    organizationName: "Aura Oncology Therapeutics",
    primaryColor: "#0284c7",
    accentColor: "#0ea5e9",
    tableHeaderColor: "#0f172a",
    headerText: "CONFIDENTIAL • CLINICAL TRIAL PROTOCOL SPECIFICATION",
    footerText: "Investigator & Data Management Working Copy",
    confidentialityNotice:
      "This document contains confidential information belonging to Aura Oncology Therapeutics. No part may be reproduced or disclosed without prior written authorization.",
    showPageNumbers: true,
    showTableOfContents: true,
  },
  codelists: [...STANDARD_CODELISTS],
  visits: [
    {
      id: "v_screen",
      oid: "SE.SCRN",
      name: "Screening (Day -28 to -1)",
      visitType: "Scheduled",
      targetDay: -1,
      windowBefore: 27,
      windowAfter: 0,
      assignedFormIds: ["form_dm_onc", "form_vs_onc", "form_lb_onc"],
    },
    {
      id: "v_c1d1",
      oid: "SE.C1D1",
      name: "Cycle 1 Day 1 (Baseline)",
      visitType: "Scheduled",
      targetDay: 1,
      windowBefore: 0,
      windowAfter: 2,
      assignedFormIds: ["form_vs_onc", "form_recist_onc", "form_lb_onc"],
    },
    {
      id: "v_c2d1",
      oid: "SE.C2D1",
      name: "Cycle 2 Day 1",
      visitType: "Scheduled",
      targetDay: 22,
      windowBefore: 3,
      windowAfter: 3,
      assignedFormIds: ["form_vs_onc", "form_lb_onc"],
    },
    {
      id: "v_c3d1",
      oid: "SE.C3D1",
      name: "Cycle 3 Day 1 (Restaging CT/MRI)",
      visitType: "Scheduled",
      targetDay: 43,
      windowBefore: 3,
      windowAfter: 3,
      assignedFormIds: ["form_vs_onc", "form_recist_onc", "form_lb_onc"],
    },
    {
      id: "v_eos",
      oid: "SE.EOS",
      name: "End of Study / Safety Follow-up",
      visitType: "Scheduled",
      targetDay: 120,
      windowBefore: 7,
      windowAfter: 7,
      assignedFormIds: ["form_vs_onc", "form_lb_onc"],
    },
    {
      id: "v_unsched",
      oid: "SE.UNSCHED",
      name: "Unscheduled Visit",
      visitType: "Unscheduled",
      targetDay: 0,
      windowBefore: 0,
      windowAfter: 0,
      assignedFormIds: ["form_vs_onc", "form_lb_onc"],
    },
  ],
  forms: [
    {
      ...scaffoldCdashDomain("DM"),
      id: "form_dm_onc",
    },
    {
      ...scaffoldCdashDomain("VS"),
      id: "form_vs_onc",
    },
    {
      ...scaffoldCdashDomain("RECIST"),
      id: "form_recist_onc",
    },
    {
      ...scaffoldCdashDomain("AE"),
      id: "form_ae_onc",
    },
    {
      ...scaffoldCdashDomain("CM"),
      id: "form_cm_onc",
    },
    {
      ...scaffoldCdashDomain("LB"),
      id: "form_lb_onc",
    },
  ],
};
