import { StudyProtocol } from "../types";
import { STANDARD_CODELISTS, scaffoldCdashDomain } from "../cdisc-cdash-library";

export const ONCOLOGY_RECIST_PRESET: StudyProtocol = {
  id: "study_onc_003",
  protocolNumber: "ONC-2026-003",
  studyName: "A Randomized, Double-Blind Phase III Study of Dual Immune Checkpoint Inhibition in Advanced Solid Tumors",
  phase: "Phase III",
  sponsor: "Aura Oncology Therapeutics",
  therapeuticArea: "Oncology",
  version: "3.2",
  lastModified: "2026-08-15",
  branding: {
    organizationName: "Aura Oncology Therapeutics",
    primaryColor: "#0284c7",
    accentColor: "#0ea5e9",
    tableHeaderColor: "#0f172a",
    headerText: "CONFIDENTIAL • CLINICAL TRIAL PROTOCOL SPECIFICATION",
    footerText: "Investigator & Data Management Working Copy",
    confidentialityNotice:
      "This document contains confidential information belonging to Aura Oncology Therapeutics. No part may be reproduced or disclosed without prior written authorization.",
    showPageNumbers: true,
    showTableOfContents: true,
  },
  codelists: [...STANDARD_CODELISTS],
  arms: [
    {
      id: "arm_exp",
      name: "Arm A: Pembrolizumab 200mg IV Q3W + Investigational Agent",
      type: "Experimental",
      description: "Active treatment combination arm",
      epochIds: ["ep_scrn", "e_trt", "e_fup"],
    },
    {
      id: "arm_ctrl",
      name: "Arm B: Standard of Care Chemotherapy",
      type: "Active Comparator",
      description: "Investigator's choice standard chemotherapy",
      epochIds: ["ep_scrn", "e_trt", "e_fup"],
    },
  ],
  epochs: [
    {
      id: "ep_scrn",
      name: "Screening Epoch",
      sequenceNumber: 1,
      type: "Screening",
      description: "Informed consent and eligibility evaluation",
    },
    {
      id: "e_trt",
      name: "Treatment Epoch",
      sequenceNumber: 2,
      type: "Treatment",
      description: "Dosing cycles and restaging tumor response assessments",
    },
    {
      id: "e_fup",
      name: "Follow-Up Epoch",
      sequenceNumber: 3,
      type: "Follow-up",
      description: "Safety and survival monitoring",
    },
  ],
  cohorts: [
    {
      id: "cohort_1",
      name: "Intent-to-Treat Cohort",
      description: "All randomized subjects",
      armIds: ["arm_exp", "arm_ctrl"],
      targetSize: 450,
    },
  ],
  biomedicalConcepts: [
    {
      id: "bc_age",
      name: "Subject Age",
      conceptId: "C25150",
      code: "C25150",
      domain: "DM",
      variableName: "AGE",
      dataType: "integer",
      label: "Age at Informed Consent",
      unit: "years",
    },
    {
      id: "bc_sysbp",
      name: "Systolic Blood Pressure",
      conceptId: "C25298",
      code: "C25298",
      domain: "VS",
      variableName: "SYSBP",
      dataType: "integer",
      label: "Systolic Blood Pressure",
      unit: "mmHg",
    },
    {
      id: "bc_diabp",
      name: "Diastolic Blood Pressure",
      conceptId: "C25299",
      code: "C25299",
      domain: "VS",
      variableName: "DIABP",
      dataType: "integer",
      label: "Diastolic Blood Pressure",
      unit: "mmHg",
    },
  ],
  visits: [
    {
      id: "v_screen",
      oid: "SE.SCRN",
      name: "Screening (Day -28 to -1)",
      visitType: "Scheduled",
      targetDay: -1,
      windowBefore: 27,
      windowAfter: 0,
      epochId: "ep_scrn",
      armIds: ["arm_exp", "arm_ctrl"],
      assignedFormIds: ["form_dm_onc", "form_vs_onc", "form_lb_onc"],
      armFormAssignments: {
        arm_exp: ["form_dm_onc", "form_vs_onc", "form_lb_onc"],
        arm_ctrl: ["form_dm_onc", "form_vs_onc", "form_lb_onc"],
      },
    },
    {
      id: "v_c1d1",
      oid: "SE.C1D1",
      name: "Cycle 1 Day 1 (Baseline)",
      visitType: "Scheduled",
      targetDay: 1,
      windowBefore: 0,
      windowAfter: 2,
      epochId: "e_trt",
      armIds: ["arm_exp", "arm_ctrl"],
      assignedFormIds: ["form_vs_onc", "form_recist_onc", "form_lb_onc"],
      armFormAssignments: {
        arm_exp: ["form_vs_onc", "form_recist_onc", "form_lb_onc"],
        arm_ctrl: ["form_vs_onc", "form_lb_onc"],
      },
    },
    {
      id: "v_c2d1",
      oid: "SE.C2D1",
      name: "Cycle 2 Day 1",
      visitType: "Scheduled",
      targetDay: 22,
      windowBefore: 3,
      windowAfter: 3,
      epochId: "e_trt",
      armIds: ["arm_exp", "arm_ctrl"],
      assignedFormIds: ["form_vs_onc", "form_lb_onc"],
    },
    {
      id: "v_c3d1",
      oid: "SE.C3D1",
      name: "Cycle 3 Day 1 (Restaging CT/MRI)",
      visitType: "Scheduled",
      targetDay: 43,
      windowBefore: 3,
      windowAfter: 3,
      epochId: "e_trt",
      armIds: ["arm_exp", "arm_ctrl"],
      assignedFormIds: ["form_vs_onc", "form_recist_onc", "form_lb_onc"],
      armFormAssignments: {
        arm_exp: ["form_vs_onc", "form_recist_onc", "form_lb_onc"],
        arm_ctrl: ["form_vs_onc", "form_lb_onc"],
      },
    },
    {
      id: "v_eos",
      oid: "SE.EOS",
      name: "End of Study / Safety Follow-up",
      visitType: "Scheduled",
      targetDay: 120,
      windowBefore: 7,
      windowAfter: 7,
      epochId: "e_fup",
      armIds: ["arm_exp", "arm_ctrl"],
      assignedFormIds: ["form_vs_onc", "form_lb_onc"],
    },
    {
      id: "v_unsched",
      oid: "SE.UNSCHED",
      name: "Unscheduled Visit",
      visitType: "Unscheduled",
      targetDay: 0,
      windowBefore: 0,
      windowAfter: 0,
      assignedFormIds: ["form_vs_onc", "form_lb_onc"],
    },
  ],
  forms: [
    {
      ...scaffoldCdashDomain("DM"),
      id: "form_dm_onc",
    },
    {
      ...scaffoldCdashDomain("VS"),
      id: "form_vs_onc",
    },
    {
      ...scaffoldCdashDomain("RECIST"),
      id: "form_recist_onc",
    },
    {
      ...scaffoldCdashDomain("AE"),
      id: "form_ae_onc",
    },
    {
      ...scaffoldCdashDomain("CM"),
      id: "form_cm_onc",
    },
    {
      ...scaffoldCdashDomain("LB"),
      id: "form_lb_onc",
    },
  ],
};
