/**
 * AUTO-GENERATED DESIGN TOKENS
 * Do not edit this file directly. Edit app/globals.css instead.
 */

export const designManifest = {
  colors: {
    /** Original CSS Variable: --background */
    "background": "#09090b",
    /** Original CSS Variable: --foreground */
    "foreground": "#fafafa",
    /** Original CSS Variable: --surface-1 */
    "surface-1": "rgba(24, 24, 27, 0.6)",
    /** Original CSS Variable: --surface-2 */
    "surface-2": "rgba(39, 39, 42, 0.4)",
    /** Original CSS Variable: --border */
    "border": "rgba(63, 63, 70, 0.5)",
    /** Original CSS Variable: --border-active */
    "border-active": "rgba(6, 182, 212, 0.4)",
    /** Original CSS Variable: --muted */
    "muted": "#71717a",
    /** Original CSS Variable: --muted-strong */
    "muted-strong": "#a1a1aa",
    /** Original CSS Variable: --brand-cyan */
    "brand-cyan": "#06b6d4",
    /** Original CSS Variable: --brand-cyan-glow */
    "brand-cyan-glow": "rgba(6, 182, 212, 0.15)",
    /** Original CSS Variable: --brand-blue */
    "brand-blue": "#3b82f6",
    /** Original CSS Variable: --brand-blue-glow */
    "brand-blue-glow": "rgba(59, 130, 246, 0.10)",
    /** Original CSS Variable: --brand-dark */
    "brand-dark": "#09090b",
    /** Original CSS Variable: --success */
    "success": "#10b981",
    /** Original CSS Variable: --error */
    "error": "#f87171",
    /** Original CSS Variable: --warning */
    "warning": "#fbbf24",
  },
  typography: {
    fonts: {
      /** Font stack for sans-serif */
      sans: "var(--font-inter), system-ui, -apple-system, sans-serif",
      /** Font stack for monospace */
      mono: "var(--font-geist-mono), ui-monospace, monospace",
    },
    sizes: {
      sm: {
        /** Original CSS Variable: --font-size-sm */
        fontSize: 13,
        /** Original CSS Variable: --line-height-sm */
        lineHeight: 18,
      }
    }
  },
  masonry: {
    /** Original CSS Variable: --layout-masonry-padding-with-stats */
    paddingWithStats: 484,
    /** Original CSS Variable: --layout-masonry-padding-without-stats */
    paddingWithoutStats: 254,
    /** Original CSS Variable: --layout-masonry-padding-with-quiz */
    paddingWithQuiz: 480,
  },
  layout: {
    /** Original CSS Variable: --layout-gap */
    gap: 16,
    /** Original CSS Variable: --layout-card-padding */
    cardPadding: 16,
  },
  breakpoints: {
    /** Original CSS Variable: --breakpoint-sm */
    "sm": 640,
    /** Original CSS Variable: --breakpoint-md */
    "md": 768,
    /** Original CSS Variable: --breakpoint-lg */
    "lg": 1024,
    /** Original CSS Variable: --breakpoint-xl */
    "xl": 1280,
    /** Original CSS Variable: --breakpoint-2xl */
    "2xl": 1536,
  },
  motion: {
    springs: {
      snappy: { type: "spring", stiffness: 380, damping: 30 },
      smooth: { type: "spring", stiffness: 80, damping: 20 },
      gentle: { type: "spring", stiffness: 60, damping: 20 },
      hero: { type: "spring", stiffness: 100, damping: 18 },
      heroBeam: { type: "spring", stiffness: 110, damping: 30 },
      timeline: { type: "spring", stiffness: 60, damping: 20 },
    }
  }
} as const;
