/**
 * AUTO-GENERATED DESIGN TOKENS
 * Do not edit this file directly. Edit app/globals.css instead.
 */

export const designManifest = {
  colors: {
    /** Original CSS Variable: --background */
    "background": "#0d0e11",
    /** Original CSS Variable: --foreground */
    "foreground": "#f4f4f6",
    /** Original CSS Variable: --surface-1 */
    "surface-1": "rgba(20, 22, 28, 0.75)",
    /** Original CSS Variable: --surface-2 */
    "surface-2": "rgba(28, 31, 39, 0.55)",
    /** Original CSS Variable: --border */
    "border": "rgba(255, 255, 255, 0.08)",
    /** Original CSS Variable: --border-active */
    "border-active": "rgba(245, 158, 11, 0.4)",
    /** Original CSS Variable: --muted */
    "muted": "#94a3b8",
    /** Original CSS Variable: --muted-strong */
    "muted-strong": "#cbd5e1",
    /** Original CSS Variable: --text-secondary */
    "text-secondary": "#94a3b8",
    /** Original CSS Variable: --brand-cyan */
    "brand-cyan": "#06b6d4",
    /** Original CSS Variable: --brand-cyan-glow */
    "brand-cyan-glow": "rgba(6, 182, 212, 0.15)",
    /** Original CSS Variable: --cyan-glow */
    "cyan-glow": "#38bdf8",
    /** Original CSS Variable: --emerald-accent */
    "emerald-accent": "#4ade80",
    /** Original CSS Variable: --badge-muted-bg */
    "badge-muted-bg": "#1e293b",
    /** Original CSS Variable: --badge-muted-text */
    "badge-muted-text": "#7dd3fc",
    /** Original CSS Variable: --brand-blue */
    "brand-blue": "#3b82f6",
    /** Original CSS Variable: --brand-blue-glow */
    "brand-blue-glow": "rgba(59, 130, 246, 0.1)",
    /** Original CSS Variable: --brand-dark */
    "brand-dark": "#0d0e11",
    /** Original CSS Variable: --success */
    "success": "#10b981",
    /** Original CSS Variable: --error */
    "error": "#f87171",
    /** Original CSS Variable: --warning */
    "warning": "#f59e0b",
  },
  typography: {
    fonts: {
      /** Font stack for sans-serif */
      sans: "var(--font-atkinson), system-ui, -apple-system, sans-serif",
      /** Font stack for heading */
      heading: "var(--font-lexend), system-ui, -apple-system, sans-serif",
      /** Font stack for monospace */
      mono: "var(--font-geist-mono), ui-monospace, monospace",
    },
    sizes: {
      sm: {
        /** Original CSS Variable: --font-size-sm */
        fontSize: 13,
        /** Original CSS Variable: --line-height-sm */
        lineHeight: 18,
      }
    }
  },
  masonry: {
    /** Original CSS Variable: --layout-masonry-padding-with-stats */
    paddingWithStats: 604,
    /** Original CSS Variable: --layout-masonry-padding-without-stats */
    paddingWithoutStats: 254,
  },
  layout: {
    /** Original CSS Variable: --layout-gap */
    gap: 16,
    /** Original CSS Variable: --layout-card-padding */
    cardPadding: 20,
    /** Original CSS Variable: --layout-header-height */
    headerHeight: 7,
    /** Original CSS Variable: --layout-footer-height */
    footerHeight: 4,
    /** Original CSS Variable: --layout-dock-height */
    dockHeight: 0,
    /** Original CSS Variable: --layout-studio-header-height */
    studioHeaderHeight: 3.5,
    /** Original CSS Variable: --layout-studio-budget */
    studioBudget: "calc(100dvh - var(--layout-header-height))",
    /** Original CSS Variable: --layout-viewport-budget */
    viewportBudget: "calc(\n    100dvh - var(--layout-header-height) - var(--layout-dock-height, 0px)\n  )",
    /** Original CSS Variable: --layout-workspace-budget */
    workspaceBudget: "calc(\n    100dvh - var(--layout-header-height) - var(--layout-dock-height, 0px) -\n      var(--layout-studio-header-height, 0px)\n  )",
  },
  breakpoints: {
    /** Original CSS Variable: --breakpoint-sm */
    "sm": 640,
    /** Original CSS Variable: --breakpoint-md */
    "md": 768,
    /** Original CSS Variable: --breakpoint-lg */
    "lg": 1024,
    /** Original CSS Variable: --breakpoint-xl */
    "xl": 1280,
    /** Original CSS Variable: --breakpoint-2xl */
    "2xl": 1536,
  },
  motion: {
    springs: {
      snappy: { type: "spring", stiffness: 380, damping: 30 },
      smooth: { type: "spring", stiffness: 80, damping: 20 },
      gentle: { type: "spring", stiffness: 60, damping: 20 },
      hero: { type: "spring", stiffness: 100, damping: 18 },
      heroBeam: { type: "spring", stiffness: 110, damping: 30 },
      timeline: { type: "spring", stiffness: 60, damping: 20 },
    }
  }
} as const;
