import { z } from "zod";

/**
 * Unwraps Zod wrapper schemas (transforms, pipes, refinements, inner types)
 * to reach the underlying validation schema structure suitable for OpenAPI conversion.
 */
function unwrapZodSchema(schema: unknown): unknown {
  let current = schema as { _def?: Record<string, unknown> } | undefined;
  while (current) {
    if (current._def?.type === "transform" || current._def?.type === "pipe") {
      current = (current._def.in ||
        current._def.innerType ||
        current._def.schema) as { _def?: Record<string, unknown> } | undefined;
    } else if (current._def?.innerType) {
      current = current._def.innerType as
        { _def?: Record<string, unknown> } | undefined;
    } else if (current._def?.schema) {
      current = current._def.schema as
        { _def?: Record<string, unknown> } | undefined;
    } else {
      break;
    }
  }
  return current;
}

/**
 * Recursively cleans JSON Schema objects generated by Zod to conform to OpenAPI 3.0 specs:
 * - Removes top-level `$schema` keywords
 * - Converts `anyOf: [S, { type: "null" }]` constructs into `S` with `nullable: true`
 * - Strips redundant regex pattern fields when standard string format is specified
 * - Removes safe integer JS boundary constraints (-9007199254740991 / 9007199254740991)
 */
function cleanOpenApiSchema(obj: unknown): unknown {
  if (obj === null || typeof obj !== "object") return obj;
  if (Array.isArray(obj)) return obj.map(cleanOpenApiSchema);

  const newObj: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key === "$schema") continue;
    newObj[key] = cleanOpenApiSchema(value);
  }

  if (Array.isArray(newObj.anyOf) && newObj.anyOf.length === 2) {
    const nullIdx = newObj.anyOf.findIndex(
      (item: unknown) =>
        item &&
        typeof item === "object" &&
        (item as Record<string, unknown>).type === "null"
    );
    if (nullIdx !== -1) {
      const otherSchema = newObj.anyOf[1 - nullIdx];
      delete newObj.anyOf;
      Object.assign(newObj, otherSchema, { nullable: true });
    }
  }

  if (typeof newObj.format === "string") {
    delete newObj.pattern;
  }

  if (newObj.minimum === -9007199254740991) {
    delete newObj.minimum;
  }
  if (newObj.maximum === 9007199254740991) {
    delete newObj.maximum;
  }

  return newObj;
}

/**
 * Programmatically converts a canonical Zod schema into an OpenAPI 3.0-compliant
 * JSON schema component definition.
 */
export function zodToOpenApi(schema: z.ZodTypeAny): Record<string, unknown> {
  const unwrapped = unwrapZodSchema(schema);
  const raw = z.toJSONSchema(unwrapped as z.ZodTypeAny, { target: "openApi3" });
  return cleanOpenApiSchema(raw) as Record<string, unknown>;
}
