import { CodelistDefinition } from "./types";

/**
 * Standard NCI Thesaurus Controlled Terminology Codelists
 */
export const STANDARD_CODELISTS: CodelistDefinition[] = [
  {
    id: "CL_NY",
    name: "No Yes Response (NY)",
    nciCodelistCode: "C66741",
    isStandard: true,
    options: [
      { code: "N", label: "No", nciCode: "C49487", order: 1 },
      { code: "Y", label: "Yes", nciCode: "C49488", order: 2 },
    ],
  },
  {
    id: "CL_SEX",
    name: "Sex (SEX)",
    nciCodelistCode: "C66742",
    isStandard: true,
    options: [
      { code: "M", label: "Male", nciCode: "C20197", order: 1 },
      { code: "F", label: "Female", nciCode: "C16576", order: 2 },
      { code: "UNDIFFERENTIATED", label: "Undifferentiated", nciCode: "C45908", order: 3 },
      { code: "UNKNOWN", label: "Unknown", nciCode: "C17998", order: 4 },
    ],
  },
  {
    id: "CL_RACE",
    name: "Race (RACE)",
    nciCodelistCode: "C74457",
    isStandard: true,
    options: [
      { code: "AMERICAN INDIAN OR ALASKA NATIVE", label: "American Indian or Alaska Native", nciCode: "C41259", order: 1 },
      { code: "ASIAN", label: "Asian", nciCode: "C41260", order: 2 },
      { code: "BLACK OR AFRICAN AMERICAN", label: "Black or African American", nciCode: "C16352", order: 3 },
      { code: "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER", label: "Native Hawaiian or Other Pacific Islander", nciCode: "C41219", order: 4 },
      { code: "WHITE", label: "White", nciCode: "C41261", order: 5 },
      { code: "OTHER", label: "Other", nciCode: "C17649", order: 6 },
    ],
  },
  {
    id: "CL_ETHNIC",
    name: "Ethnicity (ETHNIC)",
    nciCodelistCode: "C66790",
    isStandard: true,
    options: [
      { code: "HISPANIC OR LATINO", label: "Hispanic or Latino", nciCode: "C41222", order: 1 },
      { code: "NOT HISPANIC OR LATINO", label: "Not Hispanic or Latino", nciCode: "C41221", order: 2 },
      { code: "NOT REPORTED", label: "Not Reported", nciCode: "C43234", order: 3 },
      { code: "UNKNOWN", label: "Unknown", nciCode: "C17998", order: 4 },
    ],
  },
  {
    id: "CL_AESEV",
    name: "Severity / CTCAE Grade (AESEV)",
    nciCodelistCode: "C66769",
    isStandard: true,
    options: [
      { code: "GRADE 1 - MILD", label: "Grade 1 (Mild / Asymptomatic)", nciCode: "C48275", order: 1 },
      { code: "GRADE 2 - MODERATE", label: "Grade 2 (Moderate / Minimal Local Intervention)", nciCode: "C48276", order: 2 },
      { code: "GRADE 3 - SEVERE", label: "Grade 3 (Severe / Medically Significant)", nciCode: "C48277", order: 3 },
      { code: "GRADE 4 - LIFE-THREATENING", label: "Grade 4 (Life-threatening / Urgent Intervention)", nciCode: "C48278", order: 4 },
      { code: "GRADE 5 - DEATH", label: "Grade 5 (Death Related to AE)", nciCode: "C48279", order: 5 },
    ],
  },
  {
    id: "CL_AEREL",
    name: "Causality / Relationship to Study Drug (AEREL)",
    nciCodelistCode: "C66768",
    isStandard: true,
    options: [
      { code: "NOT RELATED", label: "Not Related", nciCode: "C48280", order: 1 },
      { code: "UNLIKELY RELATED", label: "Unlikely Related", nciCode: "C48281", order: 2 },
      { code: "POSSIBLY RELATED", label: "Possibly Related", nciCode: "C48282", order: 3 },
      { code: "PROBABLY RELATED", label: "Probably Related", nciCode: "C48283", order: 4 },
      { code: "DEFINITELY RELATED", label: "Definitely Related", nciCode: "C48284", order: 5 },
    ],
  },
  {
    id: "CL_AEOUT",
    name: "Outcome of Adverse Event (AEOUT)",
    nciCodelistCode: "C66767",
    isStandard: true,
    options: [
      { code: "RECOVERED/RESOLVED", label: "Recovered / Resolved", nciCode: "C49494", order: 1 },
      { code: "RECOVERING/RESOLVING", label: "Recovering / Resolving", nciCode: "C49495", order: 2 },
      { code: "NOT RECOVERED/NOT RESOLVED", label: "Not Recovered / Not Resolved", nciCode: "C49496", order: 3 },
      { code: "RECOVERED WITH SEQUELAE", label: "Recovered with Sequelae", nciCode: "C49497", order: 4 },
      { code: "FATAL", label: "Fatal", nciCode: "C49498", order: 5 },
      { code: "UNKNOWN", label: "Unknown", nciCode: "C17998", order: 6 },
    ],
  },
  {
    id: "CL_RECIST_RESP",
    name: "RECIST 1.1 Target Response (TRRESP)",
    nciCodelistCode: "C96642",
    isStandard: true,
    options: [
      { code: "CR", label: "Complete Response (CR)", nciCode: "C48270", order: 1 },
      { code: "PR", label: "Partial Response (PR)", nciCode: "C48271", order: 2 },
      { code: "SD", label: "Stable Disease (SD)", nciCode: "C48272", order: 3 },
      { code: "PD", label: "Progressive Disease (PD)", nciCode: "C48273", order: 4 },
      { code: "NE", label: "Not Evaluable (NE)", nciCode: "C48274", order: 5 },
    ],
  },
  {
    id: "CL_ROUTE",
    name: "Route of Administration (ROUTE)",
    nciCodelistCode: "C66729",
    isStandard: true,
    options: [
      { code: "ORAL", label: "Oral (PO)", nciCode: "C38288", order: 1 },
      { code: "INTRAVENOUS", label: "Intravenous (IV)", nciCode: "C38276", order: 2 },
      { code: "SUBCUTANEOUS", label: "Subcutaneous (SC)", nciCode: "C38299", order: 3 },
      { code: "INTRAMUSCULAR", label: "Intramuscular (IM)", nciCode: "C38209", order: 4 },
      { code: "TOPICAL", label: "Topical", nciCode: "C38304", order: 5 },
      { code: "INHALATION", label: "Inhalation", nciCode: "C38216", order: 6 },
    ],
  },
  {
    id: "CL_DEDEF",
    name: "Device Deficiency / Incident Type (DEDEFIC)",
    nciCodelistCode: "C112023",
    isStandard: true,
    options: [
      { code: "MALFUNCTION", label: "Device Malfunction / Failure", nciCode: "C48285", order: 1 },
      { code: "USE ERROR", label: "User / Operator Error", nciCode: "C50414", order: 2 },
      { code: "INADEQUATE LABELING", label: "Inadequate IFU / Labeling", nciCode: "C112025", order: 3 },
      { code: "EARLY DETERIORATION", label: "Premature Wear / Deterioration", nciCode: "C112026", order: 4 },
      { code: "OTHER DEFICIENCY", label: "Other Device Deficiency", nciCode: "C17649", order: 5 },
    ],
  },
  {
    id: "CL_DEREL",
    name: "Device Relationship / Causality (DEREL)",
    nciCodelistCode: "C112024",
    isStandard: true,
    options: [
      { code: "DEFINITELY RELATED", label: "Definitely Related to Device", nciCode: "C48284", order: 1 },
      { code: "PROBABLY RELATED", label: "Probably Related to Device", nciCode: "C48283", order: 2 },
      { code: "POSSIBLY RELATED", label: "Possibly Related to Device", nciCode: "C48282", order: 3 },
      { code: "NOT RELATED", label: "Not Related to Device", nciCode: "C48280", order: 4 },
      { code: "PROCEDURE RELATED", label: "Related to Implantation Procedure Only", nciCode: "C112027", order: 5 },
    ],
  },
  {
    id: "CL_DEACT",
    name: "Action Taken with Medical Device (DEACT)",
    nciCodelistCode: "C112028",
    isStandard: true,
    options: [
      { code: "EXPLANTED/REMOVED", label: "Explanted / Removed from Subject", nciCode: "C112029", order: 1 },
      { code: "REPLACED", label: "Replaced with New Device", nciCode: "C112030", order: 2 },
      { code: "REPROGRAMMED/ADJUSTED", label: "Reprogrammed / Settings Adjusted", nciCode: "C112031", order: 3 },
      { code: "REPAIRED", label: "Repaired In-Situ", nciCode: "C112032", order: 4 },
      { code: "NO ACTION TAKEN", label: "No Action Taken / Kept In-Situ", nciCode: "C48286", order: 5 },
    ],
  },
  {
    id: "CL_DISTAT",
    name: "Device Implantation / Tracking Status (DISTAT)",
    nciCodelistCode: "C112033",
    isStandard: true,
    options: [
      { code: "IMPLANTED ACTIVE", label: "Implanted & Active In-Situ", nciCode: "C112034", order: 1 },
      { code: "EXPLANTED", label: "Explanted", nciCode: "C112029", order: 2 },
      { code: "DEPLOYMENT FAILED", label: "Deployment Failed / Never Implanted", nciCode: "C112035", order: 3 },
      { code: "STORED", label: "In Site Inventory / Stored", nciCode: "C112036", order: 4 },
    ],
  },
  {
    id: "CL_DUPROC",
    name: "Procedural Deployment Success (DUPROC)",
    nciCodelistCode: "C112037",
    isStandard: true,
    options: [
      { code: "COMPLETE SUCCESS", label: "Complete Procedural Success", nciCode: "C112038", order: 1 },
      { code: "PARTIAL SUCCESS", label: "Partial Success (Sub-optimal deployment)", nciCode: "C112039", order: 2 },
      { code: "PROCEDURE ABORTED", label: "Procedure Aborted / Cancelled", nciCode: "C112040", order: 3 },
      { code: "CONVERTED SURGERY", label: "Converted to Emergent Open Surgery", nciCode: "C112041", order: 4 },
    ],
  },
  {
    id: "CL_DSCONT",
    name: "Disposition & Discontinuation Reason (DSCONT)",
    nciCodelistCode: "C66735",
    isStandard: true,
    options: [
      { code: "COMPLETED", label: "Completed Protocol Defined Period", nciCode: "C25250", order: 1 },
      { code: "ADVERSE EVENT", label: "Adverse Event / Safety Concern", nciCode: "C41331", order: 2 },
      { code: "LACK OF EFFICACY", label: "Lack of Efficacy / Disease Progression", nciCode: "C48269", order: 3 },
      { code: "WITHDRAWAL BY SUBJECT", label: "Withdrawal of Consent by Subject", nciCode: "C49491", order: 4 },
      { code: "LOST TO FOLLOW-UP", label: "Lost to Follow-Up", nciCode: "C48288", order: 5 },
      { code: "PHYSICIAN DECISION", label: "Investigator / Physician Decision", nciCode: "C49490", order: 6 },
      { code: "PROTOCOL VIOLATION", label: "Protocol Deviation / Violation", nciCode: "C49492", order: 7 },
      { code: "DEATH", label: "Death", nciCode: "C28554", order: 8 },
    ],
  },
  {
    id: "CL_DARECON",
    name: "Drug Accountability Reconciliation (DARECON)",
    nciCodelistCode: "C66736",
    isStandard: true,
    options: [
      { code: "RECONCILED", label: "Fully Reconciled (100% Accounted)", nciCode: "C49488", order: 1 },
      { code: "DISCREPANCY", label: "Discrepancy Documented", nciCode: "C48285", order: 2 },
      { code: "LOST/DESTROYED", label: "Lost / Accidental Destruction", nciCode: "C48286", order: 3 },
    ],
  },
  {
    id: "CL_DOSU",
    name: "Standard Dose Units (DOSU)",
    nciCodelistCode: "C71620",
    isStandard: true,
    options: [
      { code: "MG", label: "Milligram (mg)", nciCode: "C28253", order: 1 },
      { code: "G", label: "Gram (g)", nciCode: "C48155", order: 2 },
      { code: "MCG", label: "Microgram (mcg/µg)", nciCode: "C48153", order: 3 },
      { code: "ML", label: "Milliliter (mL)", nciCode: "C28254", order: 4 },
      { code: "MG/KG", label: "Milligrams per Kilogram (mg/kg)", nciCode: "C67417", order: 5 },
      { code: "MG/M2", label: "Milligrams per m² (mg/m²)", nciCode: "C67418", order: 6 },
      { code: "IU", label: "International Units (IU)", nciCode: "C48154", order: 7 },
      { code: "TABLETS", label: "Tablets / Capsules", nciCode: "C42998", order: 8 },
    ],
  },
  {
    id: "CL_MHCAT",
    name: "Medical History Body System (MHCAT)",
    nciCodelistCode: "C66737",
    isStandard: true,
    options: [
      { code: "CARDIOVASCULAR", label: "Cardiovascular / Vascular", nciCode: "C12727", order: 1 },
      { code: "RESPIRATORY", label: "Respiratory / Pulmonary", nciCode: "C12728", order: 2 },
      { code: "GASTROINTESTINAL", label: "Gastrointestinal / Hepatic", nciCode: "C12729", order: 3 },
      { code: "NEUROLOGICAL", label: "Neurological / Psychiatric", nciCode: "C12730", order: 4 },
      { code: "ENDOCRINE", label: "Endocrine / Metabolic (e.g. Diabetes)", nciCode: "C12731", order: 5 },
      { code: "ONCOLOGY", label: "Oncology / Prior Malignancy", nciCode: "C12732", order: 6 },
      { code: "MUSCULOSKELETAL", label: "Musculoskeletal / Rheumatology", nciCode: "C12733", order: 7 },
      { code: "OTHER", label: "Other Medical History", nciCode: "C17649", order: 8 },
    ],
  },
];
