import { CodelistDefinition, CdashVariableMetadata, CRFForm } from "./types";

/**
 * Standard NCI Thesaurus Controlled Terminology Codelists
 */
export const STANDARD_CODELISTS: CodelistDefinition[] = [
  {
    id: "CL_NY",
    name: "No Yes Response (NY)",
    nciCodelistCode: "C66741",
    isStandard: true,
    options: [
      { code: "N", label: "No", nciCode: "C49487", order: 1 },
      { code: "Y", label: "Yes", nciCode: "C49488", order: 2 },
    ],
  },
  {
    id: "CL_SEX",
    name: "Sex (SEX)",
    nciCodelistCode: "C66742",
    isStandard: true,
    options: [
      { code: "M", label: "Male", nciCode: "C20197", order: 1 },
      { code: "F", label: "Female", nciCode: "C16576", order: 2 },
      { code: "UNDIFFERENTIATED", label: "Undifferentiated", nciCode: "C45908", order: 3 },
      { code: "UNKNOWN", label: "Unknown", nciCode: "C17998", order: 4 },
    ],
  },
  {
    id: "CL_RACE",
    name: "Race (RACE)",
    nciCodelistCode: "C74457",
    isStandard: true,
    options: [
      { code: "AMERICAN INDIAN OR ALASKA NATIVE", label: "American Indian or Alaska Native", nciCode: "C41259", order: 1 },
      { code: "ASIAN", label: "Asian", nciCode: "C41260", order: 2 },
      { code: "BLACK OR AFRICAN AMERICAN", label: "Black or African American", nciCode: "C16352", order: 3 },
      { code: "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER", label: "Native Hawaiian or Other Pacific Islander", nciCode: "C41219", order: 4 },
      { code: "WHITE", label: "White", nciCode: "C41261", order: 5 },
      { code: "OTHER", label: "Other", nciCode: "C17649", order: 6 },
    ],
  },
  {
    id: "CL_ETHNIC",
    name: "Ethnicity (ETHNIC)",
    nciCodelistCode: "C66790",
    isStandard: true,
    options: [
      { code: "HISPANIC OR LATINO", label: "Hispanic or Latino", nciCode: "C41222", order: 1 },
      { code: "NOT HISPANIC OR LATINO", label: "Not Hispanic or Latino", nciCode: "C41221", order: 2 },
      { code: "NOT REPORTED", label: "Not Reported", nciCode: "C43234", order: 3 },
      { code: "UNKNOWN", label: "Unknown", nciCode: "C17998", order: 4 },
    ],
  },
  {
    id: "CL_AESEV",
    name: "Severity / CTCAE Grade (AESEV)",
    nciCodelistCode: "C66769",
    isStandard: true,
    options: [
      { code: "GRADE 1 - MILD", label: "Grade 1 (Mild / Asymptomatic)", nciCode: "C48275", order: 1 },
      { code: "GRADE 2 - MODERATE", label: "Grade 2 (Moderate / Minimal Local Intervention)", nciCode: "C48276", order: 2 },
      { code: "GRADE 3 - SEVERE", label: "Grade 3 (Severe / Medically Significant)", nciCode: "C48277", order: 3 },
      { code: "GRADE 4 - LIFE-THREATENING", label: "Grade 4 (Life-threatening / Urgent Intervention)", nciCode: "C48278", order: 4 },
      { code: "GRADE 5 - DEATH", label: "Grade 5 (Death Related to AE)", nciCode: "C48279", order: 5 },
    ],
  },
  {
    id: "CL_AEREL",
    name: "Causality / Relationship to Study Drug (AEREL)",
    nciCodelistCode: "C66768",
    isStandard: true,
    options: [
      { code: "NOT RELATED", label: "Not Related", nciCode: "C48280", order: 1 },
      { code: "UNLIKELY RELATED", label: "Unlikely Related", nciCode: "C48281", order: 2 },
      { code: "POSSIBLY RELATED", label: "Possibly Related", nciCode: "C48282", order: 3 },
      { code: "PROBABLY RELATED", label: "Probably Related", nciCode: "C48283", order: 4 },
      { code: "DEFINITELY RELATED", label: "Definitely Related", nciCode: "C48284", order: 5 },
    ],
  },
  {
    id: "CL_AEOUT",
    name: "Outcome of Adverse Event (AEOUT)",
    nciCodelistCode: "C66767",
    isStandard: true,
    options: [
      { code: "RECOVERED/RESOLVED", label: "Recovered / Resolved", nciCode: "C49494", order: 1 },
      { code: "RECOVERING/RESOLVING", label: "Recovering / Resolving", nciCode: "C49495", order: 2 },
      { code: "NOT RECOVERED/NOT RESOLVED", label: "Not Recovered / Not Resolved", nciCode: "C49496", order: 3 },
      { code: "RECOVERED WITH SEQUELAE", label: "Recovered with Sequelae", nciCode: "C49497", order: 4 },
      { code: "FATAL", label: "Fatal", nciCode: "C49498", order: 5 },
      { code: "UNKNOWN", label: "Unknown", nciCode: "C17998", order: 6 },
    ],
  },
  {
    id: "CL_RECIST_RESP",
    name: "RECIST 1.1 Target Response (TRRESP)",
    nciCodelistCode: "C96642",
    isStandard: true,
    options: [
      { code: "CR", label: "Complete Response (CR)", nciCode: "C48270", order: 1 },
      { code: "PR", label: "Partial Response (PR)", nciCode: "C48271", order: 2 },
      { code: "SD", label: "Stable Disease (SD)", nciCode: "C48272", order: 3 },
      { code: "PD", label: "Progressive Disease (PD)", nciCode: "C48273", order: 4 },
      { code: "NE", label: "Not Evaluable (NE)", nciCode: "C48274", order: 5 },
    ],
  },
  {
    id: "CL_ROUTE",
    name: "Route of Administration (ROUTE)",
    nciCodelistCode: "C66729",
    isStandard: true,
    options: [
      { code: "ORAL", label: "Oral (PO)", nciCode: "C38288", order: 1 },
      { code: "INTRAVENOUS", label: "Intravenous (IV)", nciCode: "C38276", order: 2 },
      { code: "SUBCUTANEOUS", label: "Subcutaneous (SC)", nciCode: "C38299", order: 3 },
      { code: "INTRAMUSCULAR", label: "Intramuscular (IM)", nciCode: "C38209", order: 4 },
      { code: "TOPICAL", label: "Topical", nciCode: "C38304", order: 5 },
      { code: "INHALATION", label: "Inhalation", nciCode: "C38216", order: 6 },
    ],
  },
];

/**
 * Standard CDASH 2.2 Domain Variable Catalog
 */
export const CDASH_STANDARD_VARIABLES: Record<string, CdashVariableMetadata[]> = {
  DM: [
    { domain: "DM", sdtmVariable: "BRTHYR", cdashLabel: "Year of Birth", core: "HR", acrfAnnotation: "DM.BRTHYR", dataCategory: "Topic" },
    { domain: "DM", sdtmVariable: "AGE", cdashLabel: "Age", core: "HR", acrfAnnotation: "DM.AGE", dataCategory: "Qualifier" },
    { domain: "DM", sdtmVariable: "AGEU", cdashLabel: "Age Units", core: "O", acrfAnnotation: "DM.AGEU", dataCategory: "Qualifier" },
    { domain: "DM", sdtmVariable: "SEX", cdashLabel: "Sex", core: "R", acrfAnnotation: "DM.SEX", dataCategory: "Topic", nciConceptId: "C66742" },
    { domain: "DM", sdtmVariable: "RACE", cdashLabel: "Race", core: "HR", acrfAnnotation: "DM.RACE", dataCategory: "Topic", nciConceptId: "C74457" },
    { domain: "DM", sdtmVariable: "ETHNIC", cdashLabel: "Ethnicity", core: "HR", acrfAnnotation: "DM.ETHNIC", dataCategory: "Topic", nciConceptId: "C66790" },
    { domain: "DM", sdtmVariable: "ICDAT", cdashLabel: "Informed Consent Date", core: "R", acrfAnnotation: "DS.DSSTDTC [DSDECOD=INFORMED CONSENT OBTAINED]", dataCategory: "Timing" },
  ],
  VS: [
    { domain: "VS", sdtmVariable: "VSDAT", cdashLabel: "Vital Signs Assessment Date", core: "R", acrfAnnotation: "VS.VSDTC", dataCategory: "Timing" },
    { domain: "VS", sdtmVariable: "HEIGHT", cdashLabel: "Height", core: "HR", acrfAnnotation: "VS.VSSTRESN [VSTESTCD=HEIGHT]", dataCategory: "Topic" },
    { domain: "VS", sdtmVariable: "WEIGHT", cdashLabel: "Weight", core: "HR", acrfAnnotation: "VS.VSSTRESN [VSTESTCD=WEIGHT]", dataCategory: "Topic" },
    { domain: "VS", sdtmVariable: "BMI", cdashLabel: "Body Mass Index", core: "HR", acrfAnnotation: "VS.VSSTRESN [VSTESTCD=BMI]", dataCategory: "Derived" },
    { domain: "VS", sdtmVariable: "SYSBP", cdashLabel: "Systolic Blood Pressure", core: "HR", acrfAnnotation: "VS.VSSTRESN [VSTESTCD=SYSBP]", dataCategory: "Topic" },
    { domain: "VS", sdtmVariable: "DIABP", cdashLabel: "Diastolic Blood Pressure", core: "HR", acrfAnnotation: "VS.VSSTRESN [VSTESTCD=DIABP]", dataCategory: "Topic" },
    { domain: "VS", sdtmVariable: "PULSE", cdashLabel: "Pulse Rate", core: "HR", acrfAnnotation: "VS.VSSTRESN [VSTESTCD=PULSE]", dataCategory: "Topic" },
    { domain: "VS", sdtmVariable: "TEMP", cdashLabel: "Temperature", core: "HR", acrfAnnotation: "VS.VSSTRESN [VSTESTCD=TEMP]", dataCategory: "Topic" },
    { domain: "VS", sdtmVariable: "RESP", cdashLabel: "Respiratory Rate", core: "O", acrfAnnotation: "VS.VSSTRESN [VSTESTCD=RESP]", dataCategory: "Topic" },
  ],
  AE: [
    { domain: "AE", sdtmVariable: "AETERM", cdashLabel: "Reported Term for Adverse Event", core: "R", acrfAnnotation: "AE.AETERM", dataCategory: "Topic" },
    { domain: "AE", sdtmVariable: "AESTDTC", cdashLabel: "AE Start Date/Time", core: "R", acrfAnnotation: "AE.AESTDTC", dataCategory: "Timing" },
    { domain: "AE", sdtmVariable: "AEENDTC", cdashLabel: "AE End Date/Time", core: "HR", acrfAnnotation: "AE.AEENDTC", dataCategory: "Timing" },
    { domain: "AE", sdtmVariable: "AEONGO", cdashLabel: "Ongoing Adverse Event", core: "HR", acrfAnnotation: "AE.AEENRTPT [AEENRTPT=ONGOING]", dataCategory: "Qualifier" },
    { domain: "AE", sdtmVariable: "AESEV", cdashLabel: "Severity / Grade", core: "R", acrfAnnotation: "AE.AESEV", dataCategory: "Qualifier", nciConceptId: "C66769" },
    { domain: "AE", sdtmVariable: "AESER", cdashLabel: "Serious Event", core: "R", acrfAnnotation: "AE.AESER", dataCategory: "Qualifier", nciConceptId: "C66741" },
    { domain: "AE", sdtmVariable: "AEREL", cdashLabel: "Causality / Relatedness", core: "R", acrfAnnotation: "AE.AEREL", dataCategory: "Qualifier", nciConceptId: "C66768" },
    { domain: "AE", sdtmVariable: "AEACN", cdashLabel: "Action Taken with Study Treatment", core: "R", acrfAnnotation: "AE.AEACN", dataCategory: "Qualifier" },
    { domain: "AE", sdtmVariable: "AEOUT", cdashLabel: "Outcome of Event", core: "R", acrfAnnotation: "AE.AEOUT", dataCategory: "Qualifier", nciConceptId: "C66767" },
  ],
  CM: [
    { domain: "CM", sdtmVariable: "CMTRT", cdashLabel: "Reported Name of Drug / Therapy", core: "R", acrfAnnotation: "CM.CMTRT", dataCategory: "Topic" },
    { domain: "CM", sdtmVariable: "CMINDC", cdashLabel: "Indication", core: "HR", acrfAnnotation: "CM.CMINDC", dataCategory: "Qualifier" },
    { domain: "CM", sdtmVariable: "CMDOSE", cdashLabel: "Dose per Administration", core: "HR", acrfAnnotation: "CM.CMDOSE", dataCategory: "Qualifier" },
    { domain: "CM", sdtmVariable: "CMDOSU", cdashLabel: "Dose Units", core: "HR", acrfAnnotation: "CM.CMDOSU", dataCategory: "Qualifier" },
    { domain: "CM", sdtmVariable: "CMROUTE", cdashLabel: "Route", core: "HR", acrfAnnotation: "CM.CMROUTE", dataCategory: "Qualifier", nciConceptId: "C66729" },
    { domain: "CM", sdtmVariable: "CMSTDTC", cdashLabel: "Medication Start Date", core: "R", acrfAnnotation: "CM.CMSTDTC", dataCategory: "Timing" },
    { domain: "CM", sdtmVariable: "CMENDTC", cdashLabel: "Medication End Date", core: "O", acrfAnnotation: "CM.CMENDTC", dataCategory: "Timing" },
    { domain: "CM", sdtmVariable: "CMONGO", cdashLabel: "Ongoing Medication", core: "O", acrfAnnotation: "CM.CMENRTPT [CMENRTPT=ONGOING]", dataCategory: "Qualifier" },
  ],
  LB: [
    { domain: "LB", sdtmVariable: "LBDAT", cdashLabel: "Sample Collection Date", core: "R", acrfAnnotation: "LB.LBDTC", dataCategory: "Timing" },
    { domain: "LB", sdtmVariable: "LBTEST", cdashLabel: "Lab Test Name", core: "O", acrfAnnotation: "LB.LBTEST", dataCategory: "Topic" },
    { domain: "LB", sdtmVariable: "LBORRES", cdashLabel: "Result Value", core: "O", acrfAnnotation: "LB.LBORRES", dataCategory: "Result" },
    { domain: "LB", sdtmVariable: "LBORRESU", cdashLabel: "Units", core: "O", acrfAnnotation: "LB.LBORRESU", dataCategory: "Qualifier" },
    { domain: "LB", sdtmVariable: "LBNRIND", cdashLabel: "Reference Range Indicator", core: "O", acrfAnnotation: "LB.LBNRIND", dataCategory: "Qualifier" },
    { domain: "LB", sdtmVariable: "LBCLSIG", cdashLabel: "Clinically Significant (Y/N)", core: "O", acrfAnnotation: "LB.SUPPLB.LBCLSIG", dataCategory: "Qualifier" },
  ],
};

/**
 * 1-Click CDASH Domain Auto-Scaffolder Generator
 */
export function scaffoldCdashDomain(domainCode: "DM" | "VS" | "AE" | "CM" | "LB" | "RECIST"): CRFForm {
  const formId = `form_${domainCode.toLowerCase()}_${Date.now()}`;

  switch (domainCode) {
    case "DM":
      return {
        id: formId,
        name: "Demographics & Informed Consent",
        domain: "DM",
        description: "Subject baseline characteristics, demographics, and consent tracking",
        version: "1.0",
        rules: [],
        sections: [
          {
            id: `sec_ic_${Date.now()}`,
            title: "Informed Consent",
            fields: [
              {
                id: `f_icdat_${Date.now()}`,
                variableName: "ICDAT",
                label: "Date Informed Consent Signed",
                dataType: "date",
                columnSpan: 6,
                required: true,
                cdashMetadata: CDASH_STANDARD_VARIABLES.DM.find((v) => v.sdtmVariable === "ICDAT"),
              },
              {
                id: `f_icyn_${Date.now()}`,
                variableName: "ICYN",
                label: "Did subject provide written consent prior to any protocol procedures?",
                dataType: "radio",
                columnSpan: 6,
                required: true,
                codelistId: "CL_NY",
              },
            ],
          },
          {
            id: `sec_dm_${Date.now() + 1}`,
            title: "Baseline Demographics",
            fields: [
              {
                id: `f_brthyr_${Date.now()}`,
                variableName: "BRTHYR",
                label: "Year of Birth (YYYY)",
                dataType: "integer",
                columnSpan: 4,
                required: true,
                minValue: 1900,
                maxValue: 2026,
                placeholder: "e.g. 1985",
                cdashMetadata: CDASH_STANDARD_VARIABLES.DM.find((v) => v.sdtmVariable === "BRTHYR"),
              },
              {
                id: `f_age_${Date.now() + 1}`,
                variableName: "AGE",
                label: "Age at Screening",
                dataType: "integer",
                columnSpan: 4,
                required: true,
                minValue: 18,
                maxValue: 120,
                unit: "Years",
                cdashMetadata: CDASH_STANDARD_VARIABLES.DM.find((v) => v.sdtmVariable === "AGE"),
              },
              {
                id: `f_sex_${Date.now() + 2}`,
                variableName: "SEX",
                label: "Sex assigned at birth",
                dataType: "single_select",
                columnSpan: 4,
                required: true,
                codelistId: "CL_SEX",
                cdashMetadata: CDASH_STANDARD_VARIABLES.DM.find((v) => v.sdtmVariable === "SEX"),
              },
              {
                id: `f_race_${Date.now() + 3}`,
                variableName: "RACE",
                label: "Race (Select primary)",
                dataType: "single_select",
                columnSpan: 6,
                required: true,
                codelistId: "CL_RACE",
                cdashMetadata: CDASH_STANDARD_VARIABLES.DM.find((v) => v.sdtmVariable === "RACE"),
              },
              {
                id: `f_ethnic_${Date.now() + 4}`,
                variableName: "ETHNIC",
                label: "Ethnicity",
                dataType: "single_select",
                columnSpan: 6,
                required: true,
                codelistId: "CL_ETHNIC",
                cdashMetadata: CDASH_STANDARD_VARIABLES.DM.find((v) => v.sdtmVariable === "ETHNIC"),
              },
            ],
          },
        ],
      };

    case "VS":
      return {
        id: formId,
        name: "Vital Signs & Physical Metrics",
        domain: "VS",
        description: "Sitting blood pressure, pulse, temperature, height, weight, and automated BMI",
        version: "1.0",
        rules: [
          {
            id: `rule_bmi_${Date.now()}`,
            name: "Automated BMI Derivation",
            description: "Calculate BMI automatically when height and weight are entered",
            triggerFieldIds: ["f_height", "f_weight"],
            actionType: "set_value",
            targetFieldId: "f_bmi",
            conditions: [
              { fieldId: "f_height", operator: "gt", value: 0 },
              { fieldId: "f_weight", operator: "gt", value: 0 },
            ],
            logicalOperator: "AND",
            formulaExpression: "round(weight / ((height / 100) * (height / 100)), 1)",
          },
          {
            id: `rule_sysbp_check_${Date.now() + 1}`,
            name: "Severe Hypertension Range Alert",
            description: "Raise query if Systolic BP > 180 mmHg or Diastolic > 110 mmHg",
            triggerFieldIds: ["f_sysbp", "f_diabp"],
            actionType: "raise_query",
            targetFieldId: "f_sysbp",
            conditions: [
              { fieldId: "f_sysbp", operator: "gt", value: 180 },
            ],
            logicalOperator: "OR",
            querySeverity: "warning",
            queryMessage: "Systolic Blood Pressure > 180 mmHg exceeds protocol threshold. Please confirm repeat measurement.",
          },
        ],
        sections: [
          {
            id: `sec_vs_${Date.now()}`,
            title: "Vital Signs Measurements",
            fields: [
              {
                id: "f_vsdat",
                variableName: "VSDAT",
                label: "Assessment Date & Time",
                dataType: "datetime",
                columnSpan: 6,
                required: true,
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "VSDAT"),
              },
              {
                id: "f_height",
                variableName: "HEIGHT",
                label: "Height",
                dataType: "number",
                columnSpan: 3,
                required: true,
                unit: "cm",
                minValue: 50,
                maxValue: 250,
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "HEIGHT"),
              },
              {
                id: "f_weight",
                variableName: "WEIGHT",
                label: "Weight",
                dataType: "number",
                columnSpan: 3,
                required: true,
                unit: "kg",
                minValue: 20,
                maxValue: 300,
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "WEIGHT"),
              },
              {
                id: "f_bmi",
                variableName: "BMI",
                label: "Calculated Body Mass Index (BMI)",
                dataType: "calculated",
                columnSpan: 4,
                required: false,
                readOnly: true,
                unit: "kg/m²",
                calculationFormula: "weight / ((height/100) * (height/100))",
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "BMI"),
              },
              {
                id: "f_sysbp",
                variableName: "SYSBP",
                label: "Systolic Blood Pressure",
                dataType: "integer",
                columnSpan: 4,
                required: true,
                unit: "mmHg",
                minValue: 60,
                maxValue: 260,
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "SYSBP"),
              },
              {
                id: "f_diabp",
                variableName: "DIABP",
                label: "Diastolic Blood Pressure",
                dataType: "integer",
                columnSpan: 4,
                required: true,
                unit: "mmHg",
                minValue: 30,
                maxValue: 160,
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "DIABP"),
              },
              {
                id: "f_pulse",
                variableName: "PULSE",
                label: "Heart / Pulse Rate",
                dataType: "integer",
                columnSpan: 4,
                required: true,
                unit: "beats/min",
                minValue: 30,
                maxValue: 220,
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "PULSE"),
              },
              {
                id: "f_temp",
                variableName: "TEMP",
                label: "Body Temperature",
                dataType: "number",
                columnSpan: 4,
                required: true,
                unit: "°C",
                minValue: 32.0,
                maxValue: 43.0,
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "TEMP"),
              },
              {
                id: "f_resp",
                variableName: "RESP",
                label: "Respiratory Rate",
                dataType: "integer",
                columnSpan: 4,
                required: false,
                unit: "breaths/min",
                minValue: 8,
                maxValue: 60,
                cdashMetadata: CDASH_STANDARD_VARIABLES.VS.find((v) => v.sdtmVariable === "RESP"),
              },
            ],
          },
        ],
      };

    case "AE":
      return {
        id: formId,
        name: "Adverse Events Log",
        domain: "AE",
        description: "Continuous log form for capturing adverse events, CTCAE grading, seriousness, and attribution",
        version: "1.0",
        isLogForm: true,
        rules: [
          {
            id: `rule_ae_ongo_${Date.now()}`,
            name: "Hide End Date when AE is Ongoing",
            description: "If Ongoing is checked, hide AE End Date requirement",
            triggerFieldIds: ["f_ae_ongo"],
            actionType: "hide_field",
            targetFieldId: "f_ae_endtc",
            conditions: [{ fieldId: "f_ae_ongo", operator: "eq", value: true }],
            logicalOperator: "AND",
          },
        ],
        sections: [
          {
            id: `sec_ae_${Date.now()}`,
            title: "Adverse Event Record",
            fields: [
              {
                id: "f_ae_term",
                variableName: "AETERM",
                label: "Adverse Event Reported Term (Diagnosis or Sign/Symptom)",
                dataType: "text",
                columnSpan: 12,
                required: true,
                placeholder: "e.g. Febrile Neutropenia, Peripheral Neuropathy",
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AETERM"),
              },
              {
                id: "f_ae_stdtc",
                variableName: "AESTDTC",
                label: "Start Date / Time",
                dataType: "partial_date",
                columnSpan: 4,
                required: true,
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AESTDTC"),
              },
              {
                id: "f_ae_endtc",
                variableName: "AEENDTC",
                label: "Resolution / End Date",
                dataType: "partial_date",
                columnSpan: 4,
                required: false,
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AEENDTC"),
              },
              {
                id: "f_ae_ongo",
                variableName: "AEONGO",
                label: "Event is Ongoing at time of report",
                dataType: "checkbox",
                columnSpan: 4,
                required: false,
                codelistId: "CL_NY",
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AEONGO"),
              },
              {
                id: "f_ae_sev",
                variableName: "AESEV",
                label: "Severity / CTCAE v5.0 Grade",
                dataType: "single_select",
                columnSpan: 6,
                required: true,
                codelistId: "CL_AESEV",
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AESEV"),
              },
              {
                id: "f_ae_ser",
                variableName: "AESER",
                label: "Is this a Serious Adverse Event (SAE)?",
                dataType: "radio",
                columnSpan: 6,
                required: true,
                codelistId: "CL_NY",
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AESER"),
              },
              {
                id: "f_ae_rel",
                variableName: "AEREL",
                label: "Relationship to Investigational Product",
                dataType: "single_select",
                columnSpan: 6,
                required: true,
                codelistId: "CL_AEREL",
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AEREL"),
              },
              {
                id: "f_ae_acn",
                variableName: "AEACN",
                label: "Action Taken with Study Treatment",
                dataType: "single_select",
                columnSpan: 6,
                required: true,
                customOptions: [
                  { code: "DOSE NOT CHANGED", label: "Dose Not Changed", order: 1 },
                  { code: "DOSE REDUCED", label: "Dose Reduced", order: 2 },
                  { code: "DRUG INTERRUPTED", label: "Drug Interrupted", order: 3 },
                  { code: "DRUG WITHDRAWN", label: "Drug Withdrawn", order: 4 },
                  { code: "NOT APPLICABLE", label: "Not Applicable", order: 5 },
                ],
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AEACN"),
              },
              {
                id: "f_ae_out",
                variableName: "AEOUT",
                label: "Outcome of Adverse Event",
                dataType: "single_select",
                columnSpan: 6,
                required: true,
                codelistId: "CL_AEOUT",
                cdashMetadata: CDASH_STANDARD_VARIABLES.AE.find((v) => v.sdtmVariable === "AEOUT"),
              },
            ],
          },
        ],
      };

    case "CM":
      return {
        id: formId,
        name: "Prior & Concomitant Medications",
        domain: "CM",
        description: "Log of prescription drugs, over-the-counter medications, and supplements",
        version: "1.0",
        isLogForm: true,
        rules: [],
        sections: [
          {
            id: `sec_cm_${Date.now()}`,
            title: "Medication Details",
            fields: [
              {
                id: "f_cm_trt",
                variableName: "CMTRT",
                label: "Medication / Treatment Name (Trade or Generic)",
                dataType: "text",
                columnSpan: 6,
                required: true,
                placeholder: "e.g. Paracetamol, Pembrolizumab",
                cdashMetadata: CDASH_STANDARD_VARIABLES.CM.find((v) => v.sdtmVariable === "CMTRT"),
              },
              {
                id: "f_cm_indc",
                variableName: "CMINDC",
                label: "Indication / Reason for Treatment",
                dataType: "text",
                columnSpan: 6,
                required: true,
                placeholder: "e.g. Headache, Cancer Pain",
                cdashMetadata: CDASH_STANDARD_VARIABLES.CM.find((v) => v.sdtmVariable === "CMINDC"),
              },
              {
                id: "f_cm_dose",
                variableName: "CMDOSE",
                label: "Dose per Administration",
                dataType: "number",
                columnSpan: 3,
                required: true,
                minValue: 0.1,
                cdashMetadata: CDASH_STANDARD_VARIABLES.CM.find((v) => v.sdtmVariable === "CMDOSE"),
              },
              {
                id: "f_cm_dosu",
                variableName: "CMDOSU",
                label: "Dose Unit",
                dataType: "text",
                columnSpan: 3,
                required: true,
                placeholder: "mg, mL, IU",
                cdashMetadata: CDASH_STANDARD_VARIABLES.CM.find((v) => v.sdtmVariable === "CMDOSU"),
              },
              {
                id: "f_cm_route",
                variableName: "CMROUTE",
                label: "Route of Administration",
                dataType: "single_select",
                columnSpan: 6,
                required: true,
                codelistId: "CL_ROUTE",
                cdashMetadata: CDASH_STANDARD_VARIABLES.CM.find((v) => v.sdtmVariable === "CMROUTE"),
              },
              {
                id: "f_cm_stdtc",
                variableName: "CMSTDTC",
                label: "Start Date",
                dataType: "partial_date",
                columnSpan: 6,
                required: true,
                cdashMetadata: CDASH_STANDARD_VARIABLES.CM.find((v) => v.sdtmVariable === "CMSTDTC"),
              },
              {
                id: "f_cm_endtc",
                variableName: "CMENDTC",
                label: "Stop Date",
                dataType: "partial_date",
                columnSpan: 6,
                required: false,
                cdashMetadata: CDASH_STANDARD_VARIABLES.CM.find((v) => v.sdtmVariable === "CMENDTC"),
              },
            ],
          },
        ],
      };

    case "LB":
      return {
        id: formId,
        name: "Central & Local Laboratory Panel",
        domain: "LB",
        description: "Serum chemistry, hematology, and urinalysis values",
        version: "1.0",
        rules: [],
        sections: [
          {
            id: `sec_lb_${Date.now()}`,
            title: "Blood Chemistry & Hematology",
            fields: [
              {
                id: "f_lb_dat",
                variableName: "LBDAT",
                label: "Collection Date & Time",
                dataType: "datetime",
                columnSpan: 6,
                required: true,
                cdashMetadata: CDASH_STANDARD_VARIABLES.LB.find((v) => v.sdtmVariable === "LBDAT"),
              },
              {
                id: "f_lb_fast",
                variableName: "LBFAST",
                label: "Was subject fasting >= 8 hours?",
                dataType: "radio",
                columnSpan: 6,
                required: true,
                codelistId: "CL_NY",
              },
              {
                id: "f_lb_alt",
                variableName: "ALT",
                label: "Alanine Aminotransferase (ALT/SGPT)",
                dataType: "number",
                columnSpan: 4,
                required: true,
                unit: "U/L",
                minValue: 1,
                maxValue: 2000,
              },
              {
                id: "f_lb_ast",
                variableName: "AST",
                label: "Aspartate Aminotransferase (AST/SGOT)",
                dataType: "number",
                columnSpan: 4,
                required: true,
                unit: "U/L",
                minValue: 1,
                maxValue: 2000,
              },
              {
                id: "f_lb_bili",
                variableName: "BILI",
                label: "Total Bilirubin",
                dataType: "number",
                columnSpan: 4,
                required: true,
                unit: "mg/dL",
                minValue: 0.1,
                maxValue: 40.0,
              },
              {
                id: "f_lb_creat",
                variableName: "CREAT",
                label: "Serum Creatinine",
                dataType: "number",
                columnSpan: 4,
                required: true,
                unit: "mg/dL",
                minValue: 0.1,
                maxValue: 20.0,
              },
              {
                id: "f_lb_anc",
                variableName: "ANC",
                label: "Absolute Neutrophil Count (ANC)",
                dataType: "number",
                columnSpan: 4,
                required: true,
                unit: "10^9/L",
                minValue: 0.0,
                maxValue: 50.0,
              },
              {
                id: "f_lb_plt",
                variableName: "PLAT",
                label: "Platelet Count",
                dataType: "integer",
                columnSpan: 4,
                required: true,
                unit: "10^9/L",
                minValue: 1,
                maxValue: 1500,
              },
            ],
          },
        ],
      };

    case "RECIST":
      return {
        id: formId,
        name: "Oncology RECIST 1.1 Tumor Assessment",
        domain: "TR",
        description: "Target & non-target lesion tracking with automated sum of longest diameters (SLD) and percent change from baseline",
        version: "1.0",
        rules: [
          {
            id: `rule_recist_resp_${Date.now()}`,
            name: "RECIST 1.1 Target Lesion Response Auto-Evaluation",
            description: "Derive response (PD >= +20% SLD increase, PR <= -30% SLD decrease, CR = 0mm)",
            triggerFieldIds: ["f_recist_change"],
            actionType: "set_value",
            targetFieldId: "f_recist_resp",
            conditions: [{ fieldId: "f_recist_change", operator: "is_not_empty", value: "" }],
            logicalOperator: "AND",
          },
        ],
        sections: [
          {
            id: `sec_recist_meta_${Date.now()}`,
            title: "Radiological Scan Assessment",
            fields: [
              {
                id: "f_recist_dat",
                variableName: "TRDAT",
                label: "Radiological Imaging Date (CT/MRI)",
                dataType: "date",
                columnSpan: 6,
                required: true,
              },
              {
                id: "f_recist_modality",
                variableName: "TRMETHOD",
                label: "Imaging Modality",
                dataType: "single_select",
                columnSpan: 6,
                required: true,
                customOptions: [
                  { code: "CT", label: "CT Scan with Contrast", order: 1 },
                  { code: "MRI", label: "MRI Scan", order: 2 },
                  { code: "PET_CT", label: "PET/CT Hybrid", order: 3 },
                ],
              },
            ],
          },
          {
            id: `sec_recist_target_${Date.now() + 1}`,
            title: "Target Lesion Measurements (Longest Diameter in mm)",
            fields: [
              {
                id: "f_recist_t1",
                variableName: "TRL1",
                label: "Target Lesion 1: Longest Diameter (mm) & Anatomical Site",
                dataType: "number",
                columnSpan: 6,
                required: true,
                unit: "mm",
                minValue: 0,
                maxValue: 300,
                placeholder: "e.g. 24.5",
              },
              {
                id: "f_recist_t2",
                variableName: "TRL2",
                label: "Target Lesion 2: Longest Diameter (mm) & Anatomical Site",
                dataType: "number",
                columnSpan: 6,
                required: false,
                unit: "mm",
                minValue: 0,
                maxValue: 300,
              },
              {
                id: "f_recist_sld_base",
                variableName: "TRSLDBAS",
                label: "Baseline Sum of Diameters (Reference)",
                dataType: "number",
                columnSpan: 4,
                required: true,
                unit: "mm",
                minValue: 1,
              },
              {
                id: "f_recist_sld_curr",
                variableName: "TRSLDCUR",
                label: "Current Sum of Longest Diameters (SLD)",
                dataType: "calculated",
                columnSpan: 4,
                required: false,
                readOnly: true,
                unit: "mm",
                calculationFormula: "trl1 + trl2",
              },
              {
                id: "f_recist_change",
                variableName: "TRPCTCHG",
                label: "% Change in SLD vs Baseline",
                dataType: "calculated",
                columnSpan: 4,
                required: false,
                readOnly: true,
                unit: "%",
                calculationFormula: "round(((trl1 + trl2 - trsldbas) / trsldbas) * 100, 1)",
              },
              {
                id: "f_recist_resp",
                variableName: "TRRESP",
                label: "Overall Target Lesion Response (RECIST 1.1)",
                dataType: "single_select",
                columnSpan: 12,
                required: true,
                codelistId: "CL_RECIST_RESP",
              },
            ],
          },
        ],
      };

    default:
      throw new Error(`Unsupported CDASH domain: ${domainCode}`);
  }
}
