import fs from 'fs';
import path from 'path';

const parseCSSAndGenerateTS = () => {
  const cssPath = path.resolve(process.cwd(), 'app/globals.css');
  const css = fs.readFileSync(cssPath, 'utf-8');

  // Match anything inside :root { ... }
  const rootMatch = css.match(/:root\s*{([^}]+)}/);
  if (!rootMatch) {
    console.error("Could not find :root block in globals.css");
    process.exit(1);
  }

  const rootContent = rootMatch[1];
  const tokens: Record<string, string> = {};
  
  const varRegex = /--([a-zA-Z0-9-]+)\s*:\s*([^;]+);/g;
  let match;
  while ((match = varRegex.exec(rootContent)) !== null) {
    tokens[match[1]] = match[2].trim();
  }

  const manifest: /* eslint-disable-line @typescript-eslint/no-explicit-any */ any = {
    colors: {},
    typography: { fonts: {}, sizes: {} },
    masonry: {},
    layout: {},
    motion: { springs: {} },
    breakpoints: {}
  };

  const parseNumber = (val: string, name: string) => {
    const num = parseFloat(val);
    if (isNaN(num)) {
      console.error(`Malformed token value for ${name}: ${val} is not a number.`);
      process.exit(1);
    }
    return num;
  };

  // Process colors directly
  const colorKeys = [
    'background', 'foreground', 'surface-1', 'surface-2', 
    'border', 'border-active', 'muted', 'muted-strong', 
    'brand-cyan', 'brand-cyan-glow', 'brand-blue', 'brand-blue-glow', 
    'brand-dark', 'success', 'error', 'warning'
  ];
  for (const key of colorKeys) {
    if (tokens[key]) {
      manifest.colors[key] = tokens[key];
    }
  }

  // Layout & Masonry
  for (const [key, value] of Object.entries(tokens)) {
    if (key.startsWith('layout-masonry-')) {
      const camelName = key.replace('layout-masonry-', '').replace(/-([a-z])/g, g => g[1].toUpperCase());
      manifest.masonry[camelName] = parseNumber(value, key);
    } else if (key.startsWith('layout-')) {
      const camelName = key.replace('layout-', '').replace(/-([a-z])/g, g => g[1].toUpperCase());
      const num = parseFloat(value);
      manifest.layout[camelName] = !isNaN(num) && /^[0-9.]+(px|rem|em)?$/.test(value.trim()) ? num : value;
    }
  }

  // Breakpoints
  for (const [key, value] of Object.entries(tokens)) {
    if (key.startsWith('breakpoint-')) {
      const bName = key.replace('breakpoint-', '');
      manifest.breakpoints[bName] = parseNumber(value, key);
    }
  }

  // Typography
  manifest.typography.fonts.sans = "var(--font-inter), system-ui, -apple-system, sans-serif";
  manifest.typography.fonts.mono = "var(--font-geist-mono), ui-monospace, monospace";
  manifest.typography.sizes.sm = {
    fontSize: parseNumber(tokens['font-size-sm'] || "13", 'font-size-sm'),
    lineHeight: parseNumber(tokens['line-height-sm'] || "18", 'line-height-sm')
  };

  // Motion springs
  const springsData: Record<string, /* eslint-disable-line @typescript-eslint/no-explicit-any */ any> = {};
  for (const [key, value] of Object.entries(tokens)) {
    if (key.startsWith('motion-spring-')) {
      const match = key.match(/motion-spring-(.+)-(stiffness|damping)/);
      if (match) {
        const [, name, prop] = match;
        const camelName = name.replace(/-([a-z])/g, g => g[1].toUpperCase());
        if (!springsData[camelName]) springsData[camelName] = { type: "spring" };
        springsData[camelName][prop] = parseNumber(value, key);
      }
    }
  }
  manifest.motion.springs = springsData;

  // Generate TS
  let ts = `/**\n * AUTO-GENERATED DESIGN TOKENS\n * Do not edit this file directly. Edit app/globals.css instead.\n */\n\n`;
  ts += `export const designManifest = {\n`;
  
  // Colors
  ts += `  colors: {\n`;
  for (const [k, v] of Object.entries(manifest.colors)) {
    ts += `    /** Original CSS Variable: --${k} */\n`;
    ts += `    "${k}": "${v}",\n`;
  }
  ts += `  },\n`;

  // Typography
  ts += `  typography: {\n    fonts: {\n`;
  ts += `      /** Font stack for sans-serif */\n      sans: "${manifest.typography.fonts.sans}",\n`;
  ts += `      /** Font stack for monospace */\n      mono: "${manifest.typography.fonts.mono}",\n`;
  ts += `    },\n    sizes: {\n      sm: {\n`;
  ts += `        /** Original CSS Variable: --font-size-sm */\n        fontSize: ${manifest.typography.sizes.sm.fontSize},\n`;
  ts += `        /** Original CSS Variable: --line-height-sm */\n        lineHeight: ${manifest.typography.sizes.sm.lineHeight},\n`;
  ts += `      }\n    }\n  },\n`;

  // Masonry
  ts += `  masonry: {\n`;
  for (const [k, v] of Object.entries(manifest.masonry)) {
    const cssName = `layout-masonry-${k.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`)}`;
    ts += `    /** Original CSS Variable: --${cssName} */\n`;
    ts += `    ${k}: ${v},\n`;
  }
  ts += `  },\n`;

  // Layout
  ts += `  layout: {\n`;
  for (const [k, v] of Object.entries(manifest.layout)) {
    const cssName = `layout-${k.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`)}`;
    ts += `    /** Original CSS Variable: --${cssName} */\n`;
    ts += `    ${k}: ${typeof v === "number" ? v : JSON.stringify(v)},\n`;
  }
  ts += `  },\n`;

  // Breakpoints
  ts += `  breakpoints: {\n`;
  for (const [k, v] of Object.entries(manifest.breakpoints)) {
    ts += `    /** Original CSS Variable: --breakpoint-${k} */\n`;
    ts += `    "${k}": ${v},\n`;
  }
  ts += `  },\n`;

  // Motion
  ts += `  motion: {\n    springs: {\n`;
  for (const [k, obj] of Object.entries(manifest.motion.springs)) {
    ts += `      ${k}: { type: "${(obj as   any).type}", stiffness: ${(obj as   any).stiffness}, damping: ${(obj as /* eslint-disable-line @typescript-eslint/no-explicit-any */ any).damping} },\n`;
  }
  ts += `    }\n  }\n`;

  ts += `} as const;\n`;

  const outputPath = path.resolve(process.cwd(), 'lib/design-manifest.ts');
  fs.writeFileSync(outputPath, ts);
  console.log(`Generated TS constants at ${outputPath}`);
};

parseCSSAndGenerateTS();
