import fs from 'fs';
import path from 'path';

const parseCSSAndGenerateTS = () => {
  const cssPath = path.resolve(process.cwd(), 'app/globals.css');
  const css = fs.readFileSync(cssPath, 'utf-8');

  // Match anything inside :root { ... }
  const rootMatch = css.match(/:root\s*{([^}]+)}/);
  if (!rootMatch) {
    console.error("Could not find :root block in globals.css");
    process.exit(1);
  }

  const rootContent = rootMatch[1];
  const tokens: Record<string, string> = {};
  
  const varRegex = /--([a-zA-Z0-9-]+)\s*:\s*([^;]+);/g;
  let match;
  while ((match = varRegex.exec(rootContent)) !== null) {
    tokens[match[1]] = match[2].trim();
  }

  const manifest: /* eslint-disable-line @typescript-eslint/no-explicit-any */ any = {
    colors: {},
    typography: { fonts: {}, sizes: {} },
    masonry: {},
    layout: {},
    motion: { springs: {} },
    breakpoints: {}
  };

  const parseNumber = (val: string, name: string) => {
    const num = parseFloat(val);
    if (isNaN(num)) {
      console.error(`Malformed token value for ${name}: ${val} is not a number.`);
      process.exit(1);
    }
    return num;
  };

  // Process colors directly
  const colorKeys = [
    'background', 'foreground', 'surface-1', 'surface-2', 
    'border', 'border-active', 'muted', 'muted-strong', 
    'brand-cyan', 'brand-cyan-glow', 'brand-blue', 'brand-blue-glow', 
    'brand-dark', 'success', 'error', 'warning'
  ];
  for (const key of colorKeys) {
    if (tokens[key]) {
      manifest.colors[key] = tokens[key];
    }
  }

  // Layout & Masonry
  for (const [key, value] of Object.entries(tokens)) {
    if (key.startsWith('layout-masonry-')) {
      const camelName = key.replace('layout-masonry-', '').replace(/-([a-z])/g, g => g[1].toUpperCase());
      manifest.masonry[camelName] = parseNumber(value, key);
    } else if (key.startsWith('layout-')) {
      const camelName = key.replace('layout-', '').replace(/-([a-z])/g, g => g[1].toUpperCase());
      manifest.layout[camelName] = parseNumber(value, key);
    }
  }

  // Breakpoints
  for (const [key, value] of Object.entries(tokens)) {
    if (key.startsWith('breakpoint-')) {
      const bName = key.replace('breakpoint-', '');
      manifest.breakpoints[bName] = parseNumber(value, key);
    }
  }

  // Typography
  manifest.typography.fonts.sans = "var(--font-inter), system-ui, -apple-system, sans-serif";
  manifest.typography.fonts.mono = "var(--font-geist-mono), ui-monospace, monospace";
  manifest.typography.sizes.sm = {
    fontSize: parseNumber(tokens['font-size-sm'] || "13", 'font-size-sm'),
    lineHeight: parseNumber(tokens['line-height-sm'] || "18", 'line-height-sm')
  };

  // Motion tokens (springs, durations, easings)
  const springsData: Record<string, /* eslint-disable-line @typescript-eslint/no-explicit-any */ any> = {};
  const durationsData: Record<string, number> = {};
  const easingsData: Record<string, string> = {};

  for (const [key, value] of Object.entries(tokens)) {
    if (key.startsWith('motion-spring-')) {
      const match = key.match(/motion-spring-(.+)-(stiffness|damping)/);
      if (match) {
        const [, name, prop] = match;
        const camelName = name.replace(/-([a-z])/g, g => g[1].toUpperCase());
        if (!springsData[camelName]) springsData[camelName] = { type: "spring" };
        springsData[camelName][prop] = parseNumber(value, key);
      }
    } else if (key.startsWith('motion-duration-')) {
      const dName = key.replace('motion-duration-', '').replace(/-([a-z])/g, g => g[1].toUpperCase());
      durationsData[dName] = parseNumber(value, key);
    } else if (key.startsWith('motion-ease-')) {
      const eName = key.replace('motion-ease-', '').replace(/-([a-z])/g, g => g[1].toUpperCase());
      easingsData[eName] = value;
    }
  }

  manifest.motion = {
    durations: durationsData,
    easings: easingsData,
    springs: springsData,
  };

  // Generate TS
  let ts = `/**\n * AUTO-GENERATED DESIGN TOKENS\n * Do not edit this file directly. Edit app/globals.css instead.\n */\n\n`;
  ts += `export const designManifest = {\n`;
  
  // Colors
  ts += `  colors: {\n`;
  for (const [k, v] of Object.entries(manifest.colors)) {
    ts += `    /** Original CSS Variable: --${k} */\n`;
    ts += `    "${k}": "${v}",\n`;
  }
  ts += `  },\n`;

  // Typography
  ts += `  typography: {\n    fonts: {\n`;
  ts += `      /** Font stack for sans-serif */\n      sans: "${manifest.typography.fonts.sans}",\n`;
  ts += `      /** Font stack for monospace */\n      mono: "${manifest.typography.fonts.mono}",\n`;
  ts += `    },\n    sizes: {\n      sm: {\n`;
  ts += `        /** Original CSS Variable: --font-size-sm */\n        fontSize: ${manifest.typography.sizes.sm.fontSize},\n`;
  ts += `        /** Original CSS Variable: --line-height-sm */\n        lineHeight: ${manifest.typography.sizes.sm.lineHeight},\n`;
  ts += `      }\n    }\n  },\n`;

  // Masonry
  ts += `  masonry: {\n`;
  for (const [k, v] of Object.entries(manifest.masonry)) {
    const cssName = `layout-masonry-${k.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`)}`;
    ts += `    /** Original CSS Variable: --${cssName} */\n`;
    ts += `    ${k}: ${v},\n`;
  }
  ts += `  },\n`;

  // Layout
  ts += `  layout: {\n`;
  for (const [k, v] of Object.entries(manifest.layout)) {
    const cssName = `layout-${k.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`)}`;
    ts += `    /** Original CSS Variable: --${cssName} */\n`;
    ts += `    ${k}: ${v},\n`;
  }
  ts += `  },\n`;

  // Breakpoints
  ts += `  breakpoints: {\n`;
  for (const [k, v] of Object.entries(manifest.breakpoints)) {
    ts += `    /** Original CSS Variable: --breakpoint-${k} */\n`;
    ts += `    "${k}": ${v},\n`;
  }
  ts += `  },\n`;

  // Motion
  ts += `  motion: {\n`;
  
  // Durations
  ts += `    durations: {\n`;
  for (const [k, v] of Object.entries(manifest.motion.durations)) {
    ts += `      ${k}: ${v},\n`;
  }
  ts += `    },\n`;

  // Easings
  ts += `    easings: {\n`;
  for (const [k, v] of Object.entries(manifest.motion.easings)) {
    ts += `      ${k}: "${v}",\n`;
  }
  ts += `    },\n`;

  // Springs
  ts += `    springs: {\n`;
  for (const [k, obj] of Object.entries(manifest.motion.springs)) {
    const spring = obj as { type: string; stiffness: number; damping: number };
    ts += `      ${k}: { type: "${spring.type}", stiffness: ${spring.stiffness}, damping: ${spring.damping} },\n`;
  }
  ts += `    },\n`;

  // Presets
  ts += `    presets: {\n`;
  ts += `      fadeIn: { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, transition: { duration: 0.25, ease: [0.16, 1, 0.3, 1] } },\n`;
  ts += `      scaleUp: { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, exit: { opacity: 0, scale: 0.95 }, transition: { duration: 0.15, ease: [0.16, 1, 0.3, 1] } },\n`;
  ts += `      modal: { initial: { opacity: 0, scale: 0.95, y: 8 }, animate: { opacity: 1, scale: 1, y: 0 }, exit: { opacity: 0, scale: 0.95, y: 8 }, transition: { type: "spring", stiffness: 380, damping: 30 } },\n`;
  ts += `      commandPalette: { initial: { opacity: 0, scale: 0.97, y: -8 }, animate: { opacity: 1, scale: 1, y: 0 }, exit: { opacity: 0, scale: 0.97, y: -8 }, transition: { type: "spring", stiffness: 380, damping: 30 } },\n`;
  ts += `      backdrop: { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, transition: { duration: 0.15, ease: [0.16, 1, 0.3, 1] } },\n`;
  ts += `      heroHeadline: { initial: { opacity: 0, y: 14, scale: 0.97 }, animate: { opacity: 1, y: 0, scale: 1 }, transition: { type: "spring", stiffness: 100, damping: 18 } },\n`;
  ts += `      heroText: { initial: { opacity: 0, y: 8, scale: 0.98 }, animate: { opacity: 1, y: 0, scale: 1 }, transition: { type: "spring", stiffness: 110, damping: 30 } },\n`;
  ts += `      timelineNode: { initial: { opacity: 0, y: 40 }, animate: { opacity: 1, y: 0 }, transition: { type: "spring", stiffness: 60, damping: 20 } },\n`;
  ts += `      timelineCard: { initial: { opacity: 0, y: 6 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -6 }, transition: { duration: 0.2, ease: [0.16, 1, 0.3, 1] } },\n`;
  ts += `    }\n`;

  ts += `  }\n`;

  ts += `} as const;\n\n`;

  ts += `/**\n * Resolves a motion preset with non-animating fallbacks when reduced motion is preferred.\n */\n`;
  ts += `export function resolveMotionPreset<T extends { initial?: Record<string, unknown>; animate?: Record<string, unknown>; exit?: Record<string, unknown>; transition?: Record<string, unknown> }>(\n`;
  ts += `  preset: T,\n`;
  ts += `  shouldReduceMotion?: boolean | null\n`;
  ts += `): T {\n`;
  ts += `  if (!shouldReduceMotion) return preset;\n`;
  ts += `  const sanitize = (target?: Record<string, unknown>) => {\n`;
  ts += `    if (!target) return target;\n`;
  ts += `    const copy = { ...target };\n`;
  ts += `    delete copy.x;\n`;
  ts += `    delete copy.y;\n`;
  ts += `    delete copy.scale;\n`;
  ts += `    delete copy.rotate;\n`;
  ts += `    return copy;\n`;
  ts += `  };\n`;
  ts += `  return {\n`;
  ts += `    ...preset,\n`;
  ts += `    initial: sanitize(preset.initial),\n`;
  ts += `    animate: sanitize(preset.animate),\n`;
  ts += `    exit: sanitize(preset.exit),\n`;
  ts += `    transition: { duration: 0.01 },\n`;
  ts += `  };\n`;
  ts += `}\n`;

  const outputPath = path.resolve(process.cwd(), 'lib/design-manifest.ts');
  fs.writeFileSync(outputPath, ts);
  console.log(`Generated TS constants at ${outputPath}`);
};

parseCSSAndGenerateTS();
