import fs from "node:fs";
import path from "node:path";

export interface ThemeGenerationOptions {
  sourceRoot?: string;
  outputPath?: string;
}

function parseNumber(value: string, name: string): number {
  const numberValue = Number.parseFloat(value);
  if (Number.isNaN(numberValue)) {
    throw new Error(
      `Malformed token value for ${name}: ${value} is not a number.`
    );
  }
  return numberValue;
}

function toCamelCase(value: string): string {
  return value.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
}

/** Compiles :root design tokens into the runtime TypeScript manifest. */
export function generateTheme({
  sourceRoot = process.cwd(),
  outputPath = path.resolve(sourceRoot, "lib/design-manifest.ts"),
}: ThemeGenerationOptions = {}): string {
  const cssPath = path.resolve(sourceRoot, "app/globals.css");
  const css = fs.readFileSync(cssPath, "utf8");
  const rootMatch = css.match(/:root\s*{([^}]+)}/);

  if (!rootMatch) {
    throw new Error(`Could not find a :root block in ${cssPath}.`);
  }

  const tokens: Record<string, string> = {};
  const variablePattern = /--([a-zA-Z0-9-]+)\s*:\s*([^;]+);/g;
  let match: RegExpExecArray | null;
  while ((match = variablePattern.exec(rootMatch[1])) !== null) {
    tokens[match[1]] = match[2].trim();
  }

  const colorKeys = [
    "background",
    "foreground",
    "surface-1",
    "surface-2",
    "border",
    "border-active",
    "muted",
    "muted-strong",
    "brand-cyan",
    "brand-cyan-glow",
    "brand-blue",
    "brand-blue-glow",
    "brand-dark",
    "success",
    "error",
    "warning",
  ];
  const colors = Object.fromEntries(
    colorKeys.flatMap((key) => (tokens[key] ? [[key, tokens[key]]] : []))
  );
  const masonry: Record<string, number> = {};
  const layout: Record<string, number | string> = {};
  const breakpoints: Record<string, number> = {};
  const springs: Record<
    string,
    { type: "spring"; stiffness?: number; damping?: number }
  > = {};

  for (const [key, value] of Object.entries(tokens)) {
    if (key.startsWith("layout-masonry-")) {
      masonry[toCamelCase(key.replace("layout-masonry-", ""))] = parseNumber(
        value,
        key
      );
    } else if (key.startsWith("layout-")) {
      const numberValue = Number.parseFloat(value);
      layout[toCamelCase(key.replace("layout-", ""))] =
        !Number.isNaN(numberValue) && /^[0-9.]+(px|rem|em)?$/.test(value)
          ? numberValue
          : value;
    } else if (key.startsWith("breakpoint-")) {
      breakpoints[key.replace("breakpoint-", "")] = parseNumber(value, key);
    } else if (key.startsWith("motion-spring-")) {
      const springMatch = key.match(/^motion-spring-(.+)-(stiffness|damping)$/);
      if (springMatch) {
        const [, name, property] = springMatch;
        const spring = springs[toCamelCase(name)] ?? {
          type: "spring" as const,
        };
        if (property === "stiffness") {
          spring.stiffness = parseNumber(value, key);
        } else {
          spring.damping = parseNumber(value, key);
        }
        springs[toCamelCase(name)] = spring;
      }
    }
  }

  const manifest = [
    "/**",
    " * AUTO-GENERATED DESIGN TOKENS",
    " * Do not edit this file directly. Edit app/globals.css instead.",
    " */",
    "",
    "export const designManifest = ",
    `${JSON.stringify(
      {
        colors,
        typography: {
          fonts: {
            sans: "var(--font-inter), system-ui, -apple-system, sans-serif",
            mono: "var(--font-geist-mono), ui-monospace, monospace",
          },
          sizes: {
            sm: {
              fontSize: parseNumber(
                tokens["font-size-sm"] ?? "13",
                "font-size-sm"
              ),
              lineHeight: parseNumber(
                tokens["line-height-sm"] ?? "18",
                "line-height-sm"
              ),
            },
          },
        },
        masonry,
        layout,
        breakpoints,
        motion: { springs },
      },
      null,
      2
    )} as const;`,
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  if (
    !fs.existsSync(outputPath) ||
    fs.readFileSync(outputPath, "utf8") !== manifest
  ) {
    fs.writeFileSync(outputPath, manifest, "utf8");
  }

  return manifest;
}

function readFlag(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index === -1 ? undefined : process.argv[index + 1];
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    const sourceRoot = readFlag("--source-root") ?? process.cwd();
    const outputPath = readFlag("--output");
    generateTheme({
      sourceRoot,
      ...(outputPath ? { outputPath: path.resolve(outputPath) } : {}),
    });
    console.log(
      `Generated TS constants at ${outputPath ?? path.resolve(sourceRoot, "lib/design-manifest.ts")}`
    );
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
